// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ZcuPXL0OKc1yvXvzR-fqSTg2CpqPyAc',
    appId: '1:1054200799503:web:74e2b3ba0c3102353a1e7a',
    messagingSenderId: '1054200799503',
    projectId: 'shoot-iraq',
    authDomain: 'shoot-iraq.firebaseapp.com',
    storageBucket: 'shoot-iraq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFXFmIJI9bkmlIybodmgS_zzoGv8hMtQQ',
    appId: '1:1054200799503:android:cf869bcf588ca7463a1e7a',
    messagingSenderId: '1054200799503',
    projectId: 'shoot-iraq',
    storageBucket: 'shoot-iraq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW3LjDms7wwfGo5Wh1HDd6zjbFd-3Rr58',
    appId: '1:1054200799503:ios:7c4e7f2908ada7e93a1e7a',
    messagingSenderId: '1054200799503',
    projectId: 'shoot-iraq',
    storageBucket: 'shoot-iraq.firebasestorage.app',
    iosBundleId: 'com.shootapp.shoot',
  );
}
